services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: discord_bot
      MYSQL_USER: discord_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge

volumes:
  mariadb_data: