services:
  # 数据库服务
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: discord_bot
      MYSQL_USER: discord_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  # 后端服务
  backend:
    image: backend
    container_name: backend_container
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    volumes:
      - shared_data:/data
    networks:
      - app_network

  # 前端服务
  frontend:
    image: frontend
    container_name: frontend_container
    ports:
      - "443:443"
    depends_on:
      - backend
    networks:
      - app_network

  # 機器人服務
  bot:
    image: bot
    container_name: bot_container
    depends_on:
      - mariadb
    volumes:
      - shared_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
  shared_data:
